In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("C:/Datasets/ipl2017.csv")

In [3]:
df.head()

,mid,date,venue,bat_team,bowl_team,batsman,bowler,runs,wickets,overs,runs_last_5,wickets_last_5,striker,non-striker,total
0,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,P Kumar,1,0,0.1,1,0,0,0,222
1,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,1,0,0.2,1,0,0,0,222
2,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2,0,0.2,2,0,0,0,222
3,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2,0,0.3,2,0,0,0,222
4,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2,0,0.4,2,0,0,0,222

In [4]:
y=df["total"]

In [5]:
x=df.drop("total",axis=1)

In [6]:
x.head(5)

,mid,date,venue,bat_team,bowl_team,batsman,bowler,runs,wickets,overs,runs_last_5,wickets_last_5,striker,non-striker
0,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,P Kumar,1,0,0.1,1,0,0,0
1,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,1,0,0.2,1,0,0,0
2,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2,0,0.2,2,0,0,0
3,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2,0,0.3,2,0,0,0
4,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2,0,0.4,2,0,0,0

In [7]:
x=x.drop(["mid","date","venue","bat_team","bowl_team","bowler","wickets","overs","wickets_last_5"],axis=1)

In [8]:
x.head(5)

       batsman  runs  runs_last_5  striker  non-striker
0   SC Ganguly     1            1        0            0
1  BB McCullum     1            1        0            0
2  BB McCullum     2            2        0            0
3  BB McCullum     2            2        0            0
4  BB McCullum     2            2        0            0

In [9]:
x.isna().sum()

batsman        0
runs           0
runs_last_5    0
striker        0
non-striker    0
dtype: int64

In [10]:
y.isna().sum()

0

In [11]:
type(x)

pandas.core.frame.DataFrame

In [12]:
x.dtypes

batsman        object
runs            int64
runs_last_5     int64
striker         int64
non-striker     int64
dtype: object

In [13]:
x["batsman"].unique()

array(['SC Ganguly', 'BB McCullum', 'RT Ponting', 'DJ Hussey',
       'Mohammad Hafeez', 'PA Patel', 'ML Hayden', 'MEK Hussey',
       'MS Dhoni', 'SK Raina', 'JDP Oram', 'S Badrinath', 'T Kohli',
       'YK Pathan', 'SR Watson', 'M Kaif', 'DS Lehmann', 'RA Jadeja',
       'M Rawat', 'D Salunkhe', 'SK Warne', 'SK Trivedi', 'L Ronchi',
       'ST Jayasuriya', 'DJ Thornely', 'RV Uthappa', 'PR Shah',
       'AM Nayar', 'SM Pollock', 'Harbhajan Singh', 'AC Gilchrist',
       'Y Venugopal Rao', 'VVS Laxman', 'A Symonds', 'RG Sharma',
       'SB Styris', 'AS Yadav', 'SB Bangar', 'WPUJC Vaas', 'RP Singh',
       'K Goel', 'JR Hopes', 'KC Sangakkara', 'DPMD Jayawardene',
       'Yuvraj Singh', 'IK Pathan', 'S Sohal', 'B Lee', 'PP Chawla',
       'WA Mota', 'Shahid Afridi', 'RR Sarwan', 'S Sreesanth',
       'VRV Singh', 'S Chanderpaul', 'R Dravid', 'LRPL Taylor',
       'JH Kallis', 'V Kohli', 'MV Boucher', 'P Kumar', 'SB Joshi',
       'Z Khan', 'R Vinay Kumar', 'WP Saha', 'LR Shukla', 'AB Agarkar',
       'M Kartik', 'I Sharma', 'AM Rahane', 'DJ Bravo', 'MA Khote',
       'G Gambhir', 'V Sehwag', 'S Dhawan', 'Shoaib Malik', 'MK Tiwary',
       'KD Karthik', 'R Bhatia', 'MF Maharoof', 'VY Mahesh', 'DB Das',
       'HH Gibbs', 'DNT Zoysa', 'D Kalyankrishna', 'GC Smith',
       'SA Asnodkar', 'Sohail Tanvir', 'SP Fleming', 'S Vidyut',
       'JA Morkel', 'LPC Silva', 'DB Ravi Teja', 'SE Marsh',
       'YV Takawale', 'SS Tiwary', 'RR Raje', 'Joginder Sharma',
       'MS Gony', 'M Muralitharan', 'M Ntini', 'W Jaffer', 'CL White',
       'Misbah-ul-Haq', 'DT Patil', 'A Kumble', 'DW Steyn', 'S Anirudha',
       'MM Patel', 'AB de Villiers', 'A Chopra', 'BJ Hodge', 'T Taibu',
       'Umar Gul', 'PP Ojha', 'SP Goswami', 'B Akhil', 'Salman Butt',
       'TM Dilshan', 'A Mishra', 'J Arunkumar', 'Iqbal Abdulla',
       'CK Kapugedera', 'LA Pomersbach', 'Shoaib Akhtar', 'AB Dinda',
       'SR Tendulkar', 'B Chipli', 'DR Smith', 'SD Chitnis',
       'Kamran Akmal', 'TM Srivastava', 'MK Pandey', 'RR Powar',
       'JP Duminy', 'JD Ryder', 'KP Pietersen', 'CH Gayle',
       'MC Henriques', 'A Flintoff', 'FH Edwards', 'PC Valthaty',
       'RJ Quiney', 'AD Mascarenhas', 'AS Raut', 'Pankaj Singh',
       'RS Bopara', 'DL Vettori', 'M Manhas', 'PJ Sangwan', 'MN van Wyk',
       'AA Bilakhia', 'TL Suman', 'Shoaib Ahmed', 'GR Napier',
       'R Bishnoi', 'RE van der Merwe', 'KP Appanna', 'M Vijay',
       'SB Jakati', 'L Balaji', 'NV Ojha', 'LA Carseldine', 'RJ Harris',
       'D du Preez', 'DS Kulkarni', 'SM Harwood', 'Yashpal Singh',
       'AN Ghosh', 'AD Mathews', 'SM Katich', 'DA Warner', 'J Botha',
       'A Nehra', 'Mashrafe Mortaza', 'GJ Bailey', 'AB McDonald',
       'Y Nagar', 'Niraj Patel', 'T Henderson', 'A Singh', 'R Ashwin',
       'T Thushara', 'Mohammad Ashraful', 'CA Pujara', 'OA Shah',
       'AP Tare', 'AT Rayudu', 'R Sathish', 'R McLaren', 'MS Bisla',
       'YA Abdulla', 'EJG Morgan', 'AA Jhunjhunwala', 'P Dogra',
       'A Uniyal', 'KA Pollard', 'MJ Lumb', 'DR Martyn', 'S Narwal',
       'M Morkel', 'Anirudh Singh', 'Jaskaran Singh', 'FY Fazal',
       'AC Voges', 'MD Mishra', 'J Theron', 'R Sharma', 'Mandeep Singh',
       'KM Jadhav', 'SW Tait', 'PD Collingwood', 'VS Malik',
       'SJ Srivastava', 'AP Dole', 'Bipul Sharma', 'DE Bollinger',
       'BAW Mendis', 'B Sumanth', 'C Madan', 'AG Paunikar', 'AJ Finch',
       'MR Marsh', 'STR Binny', 'IR Jaggi', 'DT Christian', 'RV Gomez',
       'UBT Chand', 'UT Yadav', 'Sunny Singh', 'NJ Rimmington',
       'MA Agarwal', 'AUK Pathan', 'AL Menaria', 'DJ Jacobs',
       'WD Parnell', 'TD Paine', 'SB Wagh', 'AC Thomas', 'BJ Haddin',
       'NLTC Perera', 'MS Wade', 'JE Taylor', 'RN ten Doeschate',
       'SL Malinga', 'AG Murtaza', 'TR Birt', 'Harpreet Singh',
       'NL McCullum', 'DH Yagnik', 'AC Blizzard', 'M Klinger',
       'I Malhotra', 'A Mithun', 'P Parameswaran', 'AA Chavan',
       'ND Doshi', 'CJ Ferguson', 'B Kumar', 'S Rana', 'JEC Franklin',
       'Shakib Al Hasan', 'F du Plessis', 'SPD Smith', 'MN Samuels',
       'KK Cooper', 'HV Patel', 'Ankit Sharma', 'RE Levi', 'RR Bhatkal',
       'Harmeet Singh', 'BA Bhatt', 'CJ McKay', 'DJ Harris', 'N Saini',
       'DA Miller', 'Azhar Mahmood', 'A Ashish Reddy', 'V Pratap Singh',
       'BB Samantray', 'RJ Peterson', 'S Nadeem', 'VR Aaron', 'MJ Clarke',
       'AP Majumdar', 'Gurkeerat Singh', 'P Awana', 'SP Narine',
       'A Chandila', 'PA Reddy', 'MC Juneja', 'AD Russell', 'KK Nair',
       'KB Arun Karthik', 'GH Vihari', 'MDKJ Perera', 'R Shukla',
       'JD Unadkat', 'M Vohra', 'JP Faulkner', 'R Rampaul', 'BJ Rohrer',
       'Q de Kock', 'KV Sharma', 'SMSM Senanayake', 'LJ Wright',
       'X Thalaivan Sargunam', 'DJG Sammy', 'MG Johnson', 'A Mukund',
       'SV Samson', 'BMAJ Mendis', 'KL Rahul', 'CM Gautam',
       'KW Richardson', 'Parvez Rasool', 'GJ Maxwell', 'R Dhawan',
       'SA Yadav', 'CJ Anderson', 'JJ Bumrah', 'CA Lynn', 'MA Starc',
       'AR Patel', 'Sandeep Sharma', 'BR Dunk', 'Shivam Sharma',
       'LMP Simmons', 'VH Zol', 'BCJ Cutting', 'Mohammed Shami',
       'BE Hendricks', 'S Gopal', 'M de Lange', 'RR Rossouw', 'JO Holder',
       'JDS Neesham', 'Imran Tahir', 'MM Sharma', 'DJ Hooda', 'CH Morris',
       'SS Iyer', 'SA Abbott', 'AN Ahmed', 'YS Chahal', 'J Suchith',
       'P Negi', 'RG More', 'Anureet Singh', 'HH Pandya',
       'NM Coulter-Nile', 'PV Tambe', 'MJ McClenaghan', 'DJ Muthuswami',
       'SN Thakur', 'SN Khan', 'D Wiese', 'S Aravind', 'JC Buttler',
       'CR Brathwaite', 'MP Stoinis', 'C Munro', 'P Sahu', 'KH Pandya',
       'TG Southee', 'MJ Guptill', 'KJ Abbott', 'TM Head', 'AD Nath',
       'NS Naik', 'Ishan Kishan', 'SW Billings', 'RR Pant',
       'KS Williamson', 'KC Cariappa', 'PSP Handscomb', 'Sachin Baby',
       'J Yadav', 'UT Khawaja', 'HM Amla', 'BB Sran', 'N Rana',
       'F Behardien', 'ER Dwivedi', 'JJ Roy', 'BA Stokes', 'Vishnu Vinod',
       'TS Mills', 'Basil Thampi', 'CR Woakes', 'V Shankar',
       'Rashid Khan', 'RA Tripathi', 'RD Chahar', 'LH Ferguson',
       'C de Grandhomme', 'PJ Cummins', 'Mohammad Nabi', 'Kuldeep Yadav',
       'Washington Sundar', 'S Badree', 'A Choudhary', 'AR Bawne',
       'AJ Tye', 'Ankit Soni', 'K Rabada', 'AF Milne', 'SP Jackson',
       'Swapnil Singh', 'R Tewatia', 'AS Rajpoot'], dtype=object)

In [14]:
x=pd.get_dummies(x,columns=["batsman"])

In [15]:
x.dtypes

runs                      int64
runs_last_5               int64
striker                   int64
non-striker               int64
batsman_A Ashish Reddy    uint8
                          ...
batsman_YS Chahal         uint8
batsman_YV Takawale       uint8
batsman_Yashpal Singh     uint8
batsman_Yuvraj Singh      uint8
batsman_Z Khan            uint8
Length: 415, dtype: object

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1,random_state=42)

In [18]:
x

,runs,runs_last_5,striker,non-striker,batsman_A Ashish Reddy,batsman_A Chandila,batsman_A Chopra,batsman_A Choudhary,batsman_A Flintoff,batsman_A Kumble,...,batsman_X Thalaivan Sargunam,batsman_Y Nagar,batsman_Y Venugopal Rao,batsman_YA Abdulla,batsman_YK Pathan,batsman_YS Chahal,batsman_YV Takawale,batsman_Yashpal Singh,batsman_Yuvraj Singh,batsman_Z Khan
0,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76009,121,40,40,12,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
76010,127,46,46,12,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
76011,128,47,47,12,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
76012,129,48,47,13,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
76013,129,47,47,13,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [19]:
from sklearn.ensemble import RandomForestRegressor

In [20]:
model=RandomForestRegressor()

In [21]:
model.fit(x_train,y_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=None, verbose=0, warm_start=False)

In [22]:
model.score(x_test,y_test)

0.7116666470965702