In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("D:/Datasets/house-votes-84.csv")

In [3]:
df

,Class Name,handicapped-infants,water-project-cost-sharing,adoption-of-the-budget-resolution,physician-fee-freeze,el-salvador-aid,religious-groups-in-schools,anti-satellite-test-ban,aid-to-nicaraguan-contras,mx-missile,immigration,synfuels-corporation-cutback,education-spending,superfund-right-to-sue,crime,duty-free-exports,export-administration-act-south-africa
0,republican,n,y,n,y,y,y,n,n,n,y,?,y,y,y,n,y
1,republican,n,y,n,y,y,y,n,n,n,n,n,y,y,y,n,?
2,democrat,?,y,y,?,y,y,n,n,n,n,y,n,y,y,n,n
3,democrat,n,y,y,n,?,y,n,n,n,n,y,n,y,n,n,y
4,democrat,y,y,y,n,y,y,n,n,n,n,y,?,y,y,y,y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
430,republican,n,n,y,y,y,y,n,n,y,y,n,y,y,y,n,y
431,democrat,n,n,y,n,n,n,y,y,y,y,n,n,n,n,n,y
432,republican,n,?,n,y,y,y,n,n,n,n,y,y,y,y,n,y
433,republican,n,n,n,y,y,y,?,?,?,?,n,y,y,y,n,y
434,republican,n,y,n,y,y,y,n,n,n,y,n,y,y,y,?,n

In [4]:
df.isna().sum()

Class Name                                 0
 handicapped-infants                       0
 water-project-cost-sharing                0
 adoption-of-the-budget-resolution         0
 physician-fee-freeze                      0
 el-salvador-aid                           0
 religious-groups-in-schools               0
 anti-satellite-test-ban                   0
 aid-to-nicaraguan-contras                 0
 mx-missile                                0
 immigration                               0
 synfuels-corporation-cutback              0
 education-spending                        0
 superfund-right-to-sue                    0
 crime                                     0
 duty-free-exports                         0
 export-administration-act-south-africa    0
dtype: int64

In [5]:
import numpy as np

In [6]:
df.replace("?",np.nan,inplace=True)

In [7]:
df

,Class Name,handicapped-infants,water-project-cost-sharing,adoption-of-the-budget-resolution,physician-fee-freeze,el-salvador-aid,religious-groups-in-schools,anti-satellite-test-ban,aid-to-nicaraguan-contras,mx-missile,immigration,synfuels-corporation-cutback,education-spending,superfund-right-to-sue,crime,duty-free-exports,export-administration-act-south-africa
0,republican,n,y,n,y,y,y,n,n,n,y,NaN,y,y,y,n,y
1,republican,n,y,n,y,y,y,n,n,n,n,n,y,y,y,n,NaN
2,democrat,NaN,y,y,NaN,y,y,n,n,n,n,y,n,y,y,n,n
3,democrat,n,y,y,n,NaN,y,n,n,n,n,y,n,y,n,n,y
4,democrat,y,y,y,n,y,y,n,n,n,n,y,NaN,y,y,y,y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
430,republican,n,n,y,y,y,y,n,n,y,y,n,y,y,y,n,y
431,democrat,n,n,y,n,n,n,y,y,y,y,n,n,n,n,n,y
432,republican,n,NaN,n,y,y,y,n,n,n,n,y,y,y,y,n,y
433,republican,n,n,n,y,y,y,NaN,NaN,NaN,NaN,n,y,y,y,n,y
434,republican,n,y,n,y,y,y,n,n,n,y,n,y,y,y,NaN,n

In [8]:
df.isna().sum()

Class Name                                   0
 handicapped-infants                        12
 water-project-cost-sharing                 48
 adoption-of-the-budget-resolution          11
 physician-fee-freeze                       11
 el-salvador-aid                            15
 religious-groups-in-schools                11
 anti-satellite-test-ban                    14
 aid-to-nicaraguan-contras                  15
 mx-missile                                 22
 immigration                                 7
 synfuels-corporation-cutback               21
 education-spending                         31
 superfund-right-to-sue                     25
 crime                                      17
 duty-free-exports                          28
 export-administration-act-south-africa    104
dtype: int64

In [9]:
df.shape

(435, 17)

In [10]:
df

,Class Name,handicapped-infants,water-project-cost-sharing,adoption-of-the-budget-resolution,physician-fee-freeze,el-salvador-aid,religious-groups-in-schools,anti-satellite-test-ban,aid-to-nicaraguan-contras,mx-missile,immigration,synfuels-corporation-cutback,education-spending,superfund-right-to-sue,crime,duty-free-exports,export-administration-act-south-africa
0,republican,n,y,n,y,y,y,n,n,n,y,NaN,y,y,y,n,y
1,republican,n,y,n,y,y,y,n,n,n,n,n,y,y,y,n,NaN
2,democrat,NaN,y,y,NaN,y,y,n,n,n,n,y,n,y,y,n,n
3,democrat,n,y,y,n,NaN,y,n,n,n,n,y,n,y,n,n,y
4,democrat,y,y,y,n,y,y,n,n,n,n,y,NaN,y,y,y,y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
430,republican,n,n,y,y,y,y,n,n,y,y,n,y,y,y,n,y
431,democrat,n,n,y,n,n,n,y,y,y,y,n,n,n,n,n,y
432,republican,n,NaN,n,y,y,y,n,n,n,n,y,y,y,y,n,y
433,republican,n,n,n,y,y,y,NaN,NaN,NaN,NaN,n,y,y,y,n,y
434,republican,n,y,n,y,y,y,n,n,n,y,n,y,y,y,NaN,n

In [ ]:
1. Subset your column of interest
2. Convert it to boolean based on condition
3. surround with variablename[..code uptil step 2..]

In [14]:
republican=df[df["Class Name"]=="republican"]

In [15]:
democrat=df[df["Class Name"]=="democrat"]

In [16]:
df.shape

(435, 17)

In [17]:
republican.shape

(168, 17)

In [18]:
democrat.shape

(267, 17)

In [21]:
republican.columns

Index(['Class Name', ' handicapped-infants', ' water-project-cost-sharing',
       ' adoption-of-the-budget-resolution', ' physician-fee-freeze',
       ' el-salvador-aid', ' religious-groups-in-schools',
       ' anti-satellite-test-ban', ' aid-to-nicaraguan-contras', ' mx-missile',
       ' immigration', ' synfuels-corporation-cutback', ' education-spending',
       ' superfund-right-to-sue', ' crime', ' duty-free-exports',
       ' export-administration-act-south-africa'],
      dtype='object')

In [31]:
republican[' handicapped-infants']=republican[' handicapped-infants'].fillna(republican[' handicapped-infants'].mode()[0])

<ipython-input-31-11b98f179c6e>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  republican[' handicapped-infants']=republican[' handicapped-infants'].fillna(republican[' handicapped-infants'].mode()[0])

In [30]:
republican[' handicapped-infants'].mode()[0]

'n'

In [32]:
republican.isna().sum()

Class Name                                  0
 handicapped-infants                        0
 water-project-cost-sharing                20
 adoption-of-the-budget-resolution          4
 physician-fee-freeze                       3
 el-salvador-aid                            3
 religious-groups-in-schools                2
 anti-satellite-test-ban                    6
 aid-to-nicaraguan-contras                 11
 mx-missile                                 3
 immigration                                3
 synfuels-corporation-cutback               9
 education-spending                        13
 superfund-right-to-sue                    10
 crime                                      7
 duty-free-exports                         12
 export-administration-act-south-africa    22
dtype: int64

In [33]:
for columnName in republican.columns:
    republican[columnName]=republican[columnName].fillna(republican[columnName].mode()[0])

<ipython-input-33-98176d2e6c84>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  republican[columnName]=republican[columnName].fillna(republican[columnName].mode()[0])

In [34]:
republican.isna().sum()

Class Name                                 0
 handicapped-infants                       0
 water-project-cost-sharing                0
 adoption-of-the-budget-resolution         0
 physician-fee-freeze                      0
 el-salvador-aid                           0
 religious-groups-in-schools               0
 anti-satellite-test-ban                   0
 aid-to-nicaraguan-contras                 0
 mx-missile                                0
 immigration                               0
 synfuels-corporation-cutback              0
 education-spending                        0
 superfund-right-to-sue                    0
 crime                                     0
 duty-free-exports                         0
 export-administration-act-south-africa    0
dtype: int64

In [35]:
for columnName in democrat.columns:
    democrat[columnName]=democrat[columnName].fillna(democrat[columnName].mode()[0])

<ipython-input-35-1767d72ea4dc>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  democrat[columnName]=democrat[columnName].fillna(democrat[columnName].mode()[0])

In [36]:
democrat.isna().sum()

Class Name                                 0
 handicapped-infants                       0
 water-project-cost-sharing                0
 adoption-of-the-budget-resolution         0
 physician-fee-freeze                      0
 el-salvador-aid                           0
 religious-groups-in-schools               0
 anti-satellite-test-ban                   0
 aid-to-nicaraguan-contras                 0
 mx-missile                                0
 immigration                               0
 synfuels-corporation-cutback              0
 education-spending                        0
 superfund-right-to-sue                    0
 crime                                     0
 duty-free-exports                         0
 export-administration-act-south-africa    0
dtype: int64

In [39]:
data=pd.concat([republican,democrat],axis=0)

In [40]:
data.shape

(435, 17)

# 1

In [46]:
X=data.drop("Class Name",axis=1)

In [47]:
X.head()

,handicapped-infants,water-project-cost-sharing,adoption-of-the-budget-resolution,physician-fee-freeze,el-salvador-aid,religious-groups-in-schools,anti-satellite-test-ban,aid-to-nicaraguan-contras,mx-missile,immigration,synfuels-corporation-cutback,education-spending,superfund-right-to-sue,crime,duty-free-exports,export-administration-act-south-africa
0,n,y,n,y,y,y,n,n,n,y,n,y,y,y,n,y
1,n,y,n,y,y,y,n,n,n,n,n,y,y,y,n,y
7,n,y,n,y,y,y,n,n,n,n,n,n,y,y,n,y
8,n,y,n,y,y,y,n,n,n,n,n,y,y,y,n,y
10,n,y,n,y,y,n,n,n,n,n,n,y,y,y,n,n

In [48]:
y=data["Class Name"]

In [49]:
X.isna().sum()

 handicapped-infants                       0
 water-project-cost-sharing                0
 adoption-of-the-budget-resolution         0
 physician-fee-freeze                      0
 el-salvador-aid                           0
 religious-groups-in-schools               0
 anti-satellite-test-ban                   0
 aid-to-nicaraguan-contras                 0
 mx-missile                                0
 immigration                               0
 synfuels-corporation-cutback              0
 education-spending                        0
 superfund-right-to-sue                    0
 crime                                     0
 duty-free-exports                         0
 export-administration-act-south-africa    0
dtype: int64

In [51]:
y.isna().sum()

0

In [52]:
X.dtypes

 handicapped-infants                       object
 water-project-cost-sharing                object
 adoption-of-the-budget-resolution         object
 physician-fee-freeze                      object
 el-salvador-aid                           object
 religious-groups-in-schools               object
 anti-satellite-test-ban                   object
 aid-to-nicaraguan-contras                 object
 mx-missile                                object
 immigration                               object
 synfuels-corporation-cutback              object
 education-spending                        object
 superfund-right-to-sue                    object
 crime                                     object
 duty-free-exports                         object
 export-administration-act-south-africa    object
dtype: object

In [53]:
X=pd.get_dummies(X,columns=X.columns)

In [54]:
X.dtypes

 handicapped-infants_n                       uint8
 handicapped-infants_y                       uint8
 water-project-cost-sharing_n                uint8
 water-project-cost-sharing_y                uint8
 adoption-of-the-budget-resolution_n         uint8
 adoption-of-the-budget-resolution_y         uint8
 physician-fee-freeze_n                      uint8
 physician-fee-freeze_y                      uint8
 el-salvador-aid_n                           uint8
 el-salvador-aid_y                           uint8
 religious-groups-in-schools_n               uint8
 religious-groups-in-schools_y               uint8
 anti-satellite-test-ban_n                   uint8
 anti-satellite-test-ban_y                   uint8
 aid-to-nicaraguan-contras_n                 uint8
 aid-to-nicaraguan-contras_y                 uint8
 mx-missile_n                                uint8
 mx-missile_y                                uint8
 immigration_n                               uint8
 immigration_y                               uint8
 synfuels-corporation-cutback_n              uint8
 synfuels-corporation-cutback_y              uint8
 education-spending_n                        uint8
 education-spending_y                        uint8
 superfund-right-to-sue_n                    uint8
 superfund-right-to-sue_y                    uint8
 crime_n                                     uint8
 crime_y                                     uint8
 duty-free-exports_n                         uint8
 duty-free-exports_y                         uint8
 export-administration-act-south-africa_n    uint8
 export-administration-act-south-africa_y    uint8
dtype: object

In [55]:
type(X)

pandas.core.frame.DataFrame

In [56]:
X.shape

(435, 32)

# 2

In [57]:
from sklearn.model_selection import train_test_split

In [58]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42,stratify=y)

In [59]:
X.head()

,handicapped-infants_n,handicapped-infants_y,water-project-cost-sharing_n,water-project-cost-sharing_y,adoption-of-the-budget-resolution_n,adoption-of-the-budget-resolution_y,physician-fee-freeze_n,physician-fee-freeze_y,el-salvador-aid_n,el-salvador-aid_y,...,education-spending_n,education-spending_y,superfund-right-to-sue_n,superfund-right-to-sue_y,crime_n,crime_y,duty-free-exports_n,duty-free-exports_y,export-administration-act-south-africa_n,export-administration-act-south-africa_y
0,1,0,0,1,1,0,0,1,0,1,...,0,1,0,1,0,1,1,0,0,1
1,1,0,0,1,1,0,0,1,0,1,...,0,1,0,1,0,1,1,0,0,1
7,1,0,0,1,1,0,0,1,0,1,...,1,0,0,1,0,1,1,0,0,1
8,1,0,0,1,1,0,0,1,0,1,...,0,1,0,1,0,1,1,0,0,1
10,1,0,0,1,1,0,0,1,0,1,...,0,1,0,1,0,1,1,0,1,0

# 3

In [60]:
from sklearn.ensemble import RandomForestClassifier

In [85]:
model=RandomForestClassifier(n_estimators=200,oob_score=True)

In [86]:
model.fit(X_train,y_train)

RandomForestClassifier(n_estimators=200, oob_score=True)

# 4

In [87]:
model.score(X_test,y_test)

0.9694656488549618

In [88]:
model.oob_score_

0.9671052631578947